package com.notrlyanurag.ws.emailnotification;

public class NotRetryableException extends RuntimeException {

  public NotRetryableException(String message) {
    super(message);
    // TODO Autogenerated constructor stub
  }

  public NotRetryableException(Throwable cause) {
    super(cause);
    // TODO Autogenerated constructor stub
  }
}
